<a href="https://colab.research.google.com/github/rujool11/ML-learning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Basics of Tensors---->**
intro to tensors

manipulating tensors

tensors and numpy

using @tf.function

### **creating tensors with ``tf.cosntant()``**

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.13.0


In [ ]:
# creating tensors using tf.constant() (mostly we won't need this a lot, tf creates tensors for you)
scalar = tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [ ]:
# getting number of dimensions (ndim)
scalar.ndim

0

In [ ]:
vector = tf.constant([10,15])
vector.ndim

1

In [ ]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 15], dtype=int32)>

In [ ]:
# matrix
matrix = tf.constant([[10,7],[15,20]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [15, 20]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#another matrix
matrix_2 = tf.constant(
    [[10.,7.],
    [5.,15.],
     [4.5,6.]], dtype=tf.float16
)
matrix_2 #set datatype to float this time, 16 bit precision

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10. ,  7. ],
       [ 5. , 15. ],
       [ 4.5,  6. ]], dtype=float16)>

In [ ]:
matrix_2.ndim

2

In [ ]:
matrix_3 = tf.constant(
    [[[3.4,3.1],
     [3.4,2.1]],
     [[1.1,1.2],
      [1.1,0.9]]]
)
matrix_3

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[3.4, 3.1],
        [3.4, 2.1]],

       [[1.1, 1.2],
        [1.1, 0.9]]], dtype=float32)>

In [ ]:
matrix_3.ndim

3

Scalar - single number

vector - number with direction (like an array)

matrix - 2D array of numbers

tensor - n dimensional array of numnbers, where (n>=0)

### **creating tensors with ``tf.Variable()``**

---



In [ ]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0] = 11
changeable_tensor

TypeError: ignored

In [ ]:
# trying .assign()
changeable_tensor[0].assign(11)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([11,  7], dtype=int32)>

In [ ]:
unchangeable_tensor[0] = 11

TypeError: ignored

In [ ]:
unchangeable_tensor[0].assign(11)

AttributeError: ignored

In [ ]:
# tensors created using .constant() cannot be changed, whereas those created using .Variable() can be changed , using .assign()

### **creating random tensors**

In [ ]:
# creating two random (but the same ) tensors
rand_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
rand_1 = rand_1.normal(shape=(3, 2))
rand_2 = tf.random.Generator.from_seed(42)
rand_2 = rand_2.normal(shape=(3, 2))
rand_1, rand_2, rand_1 == rand_2  # using a seed ensures that both the tensors come out the same even though we used random
# pseudo random numbers, generator from normal distrubution using a seed

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### **shuffling order of elements in a tensor**



In [ ]:
# valuable for when you want to shuffle data, to avoid inherent order form affecting learning
not_shuffled = tf.constant(
    [[10,7],
    [2,3],
    [11,19]]
)
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  3],
       [11, 19]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 19],
       [ 2,  3],
       [10,  7]], dtype=int32)>

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  3],
       [11, 19]], dtype=int32)>

In [ ]:
# we can see that the not_shuffled tensor is still not shuffled, to shuffle we will have to assign it to itself or another variable
shuffled = tf.random.shuffle(not_shuffled)
shuffled, not_shuffled, shuffled == not_shuffled

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 2,  3],
        [11, 19],
        [10,  7]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 2,  3],
        [11, 19]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [ ]:
# can set seed for this as well
shuffled_2 = tf.random.shuffle(not_shuffled, seed=4)
shuffled_2, not_shuffled, shuffled_2 == not_shuffled

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 2,  3],
        [11, 19],
        [10,  7]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 2,  3],
        [11, 19]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [ ]:
tf.random.set_seed(42) # global level seed
tf.random.shuffle(not_shuffled, seed=42) # operational level random seed, set both to ensure reproducibility

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  3],
       [11, 19]], dtype=int32)>

if we want to ensure same order, use global level random seed as well as operational level random seed (for reproducibility)

In [ ]:
# use numpy with tf, create a tensor of all ones
tf.ones([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([5,6]) # numpy functions ones and zeros, similar in tf

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

### **numpy arrays to tensors-->**
difference between numpy arrays and tensors is that tensorf can me run on a GPU / TPU much faster

In [ ]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
# turning into a tensor
A = tf.constant(numpy_A)
B = tf.constant(numpy_A,shape=(2, 3, 4))
A, B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

In [ ]:
B.ndim

3

### **getting information from tensors**

shape - length of each dimension of tensor

rank - no. of dimensions

axis or dimension - particular dimension , eg. tensor[0], tensor[:,1]

size - total no. of items

In [ ]:
# tensor of rank 4
t_r_4 = tf.zeros(shape=(2,3,4,5))
t_r_4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
t_r_4[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
t_r_4.ndim

4

In [ ]:
tf.size(t_r_4) # 2*3*4*5

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [ ]:
print("data type of every element : ", t_r_4.dtype)
print("no. of dimensions (rank) : ", t_r_4.ndim)
print("shape of tensor : ", t_r_4.shape)
print("no. of elements along 0 axis : ", t_r_4.shape[0])
print("no. of elements along last axis : ", t_r_4.shape[-1])
print("total no. of elements (size) : ", tf.size(t_r_4))
print("total no. of elements (size) : ", tf.size(t_r_4).numpy()) # .numpy() changes it to a numpy integer

data type of every element :  <dtype: 'float32'>
no. of dimensions (rank) :  4
shape of tensor :  (2, 3, 4, 5)
no. of elements along 0 axis :  2
no. of elements along last axis :  5
total no. of elements (size) :  tf.Tensor(120, shape=(), dtype=int32)
total no. of elements (size) :  120


### **Indexing Tensors** (similar to python lists)

In [ ]:
t_r_4[:2,:2,:2,:2] #first 2 elements of each dimension

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#first element from every dimension except final one
t_r_4[:1, :1, :1, :] # :x means until x, excluding xth index, y:x means the same, but starts from yth index

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
t_r_4[:1, :1, :, :2]

<tf.Tensor: shape=(1, 1, 4, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# create a rank 2 tensor,
t_r_2 = tf.constant([[11,9],[7,6]])
t_r_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  9],
       [ 7,  6]], dtype=int32)>

In [ ]:
t_r_2[:,-1] #last element of each row

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([9, 6], dtype=int32)>

In [ ]:
# adding an extra dimension to t_r_2, making  t_r_3
t_r_3 = t_r_2[..., tf.newaxis] # notation used to specify every axis before the last one, (like [:,:,tf.newaxis])
t_r_3,

(<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[11],
         [ 9]],
 
        [[ 7],
         [ 6]]], dtype=int32)>,)

In [ ]:
# alternative to newaxis
tf.expand_dims(t_r_2, axis=-1) # -1 used to specify axis added at end, 0 would give shape (1,2,2) and 1 would give (2,1,2)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[11],
        [ 9]],

       [[ 7],
        [ 6]]], dtype=int32)>

### **Manipulating Tensors**

In [ ]:
tensor = tf.constant(
    [[7,9],
     [10,11]]
)

tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[17, 19],
       [20, 21]], dtype=int32)>

In [ ]:
tensor #original tensor is not changed, will change only when we reassign
# all arithmetic operations can be applied to tensors

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7,  9],
       [10, 11]], dtype=int32)>

In [ ]:
tf.multiply(tensor,10)
# tensorflow operator functions such as tf.multiply(..), tf.add(..), etc make your computations faster, and use GPU/TPU acceleration

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 70,  90],
       [100, 110]], dtype=int32)>

### **Matrix multiplication**

In [ ]:
print(tensor)

tf.Tensor(
[[ 7  9]
 [10 11]], shape=(2, 2), dtype=int32)


In [ ]:
tf.matmul(tensor,tensor)  # actually tf.linalg.matmul(), but linalg can be dopped

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[139, 162],
       [180, 211]], dtype=int32)>

In [ ]:
# @ operator in python for matrix multiplication
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[139, 162],
       [180, 211]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7,  9],
       [10, 11]], dtype=int32)>

In [ ]:
t_1 = tf.constant([2,3,4,2,3,4],shape=(3, 2))
t_2 = tf.constant([i for i in range(1,10)], shape=(3, 3))
t_1, t_2

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 3],
        [4, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=int32)>)

In [ ]:
tf.matmul(t_1,t_2)

InvalidArgumentError: ignored

In [ ]:
t_1 = tf.reshape(t_1,shape=(2, 3))
t_1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [2, 3, 4]], dtype=int32)>

In [ ]:
tf.matmul(t_1,t_2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[42, 51, 60],
       [42, 51, 60]], dtype=int32)>

In [ ]:
t_3 = tf.constant([i for i in range(1,12,2)],shape=(2, 3))
t_3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  3,  5],
       [ 7,  9, 11]], dtype=int32)>

In [ ]:
t_4 = tf.matmul(t_1,t_2)
tf.matmul(t_4,tf.reshape(t_3,shape=(3, 2)))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 837, 1143],
       [ 837, 1143]], dtype=int32)>

In [ ]:
t_3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  3,  5],
       [ 7,  9, 11]], dtype=int32)>

In [ ]:
tf.matmul(t_4,tf.transpose(t_3))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 495, 1413],
       [ 495, 1413]], dtype=int32)>

### **Changing datatype of tensors**



In [ ]:
t_A = tf.constant([1.7,1.]) # default datatype .float32
t_B = tf.constant([2,3]) #default datatype .int32
t_A, t_B

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 1. ], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>)

In [ ]:
# suppose we want to change 32 but it to 16 bit (changing the precision, may be used to make model run faster)
tf.cast(t_A, dtype=tf.float16)

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 1. ], dtype=float16)>

### **Aggregating tensors**

condensing them from multiple values to a smaller amount of values

In [ ]:
# get the absolute values (not the best form, demonstarted for completeness)
D = tf.constant([-7,-10])
tf.abs(D) # absolute values

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
# min, max, mean, sum
t_rand = tf.constant(np.random.randint(0,100,size=50))
tf.size(t_rand), t_rand.shape, t_rand.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
tf.reduce_min(t_rand), tf.reduce_max(t_rand), tf.reduce_sum(t_rand), tf.reduce_mean(t_rand)

(<tf.Tensor: shape=(), dtype=int64, numpy=2>,
 <tf.Tensor: shape=(), dtype=int64, numpy=99>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2518>,
 <tf.Tensor: shape=(), dtype=int64, numpy=50>)

In [ ]:
tf.math.reduce_variance(tf.cast(t_rand,dtype=tf.float16)) # some methods dont have alias, have to use tf.math.xy(..)

<tf.Tensor: shape=(), dtype=float16, numpy=845.0>

In [ ]:
# for reduce_std, and reduce_variance, the input needs to be real of complex tensor (float, not int)

In [ ]:
tf.math.reduce_std(tf.cast(t_rand,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.070093>

### **Finding positional maximum and minimum**



In [ ]:
E = tf.random.uniform(shape=[50])
E

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(E), tf.argmin(E) # gives index of max and min positions respectively

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=int64, numpy=16>)

In [ ]:
E[tf.argmax(E)] == tf.reduce_max(E) # to check, gives true since both are equal

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
assert E[tf.argmax(E)] == tf.reduce_max(E) # we get no error, (eg. assert False would be an error)

### **Squeezing Tensor**

removing single dimensions

In [ ]:
F = tf.random.uniform(shape=[1,1,1,50])
F

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.95831835, 0.01680839, 0.3156035 , 0.16013157, 0.7148702 ,
          0.7892921 , 0.11484027, 0.33310425, 0.21091413, 0.62329304,
          0.9865029 , 0.12230623, 0.20660043, 0.87113273, 0.0206511 ,
          0.21824265, 0.6902214 , 0.70987105, 0.8787489 , 0.4835763 ,
          0.70464134, 0.6632365 , 0.55479586, 0.26258492, 0.9439995 ,
          0.45319557, 0.7687681 , 0.7587366 , 0.69659543, 0.21926284,
          0.70087314, 0.25340438, 0.90830326, 0.7034081 , 0.7037233 ,
          0.64923763, 0.9166089 , 0.3040645 , 0.38809192, 0.89422333,
          0.5430906 , 0.76366544, 0.3022945 , 0.4008665 , 0.57017696,
          0.7107911 , 0.424469  , 0.5174569 , 0.6263735 , 0.17961347]]]],
      dtype=float32)>

In [ ]:
F_squeezed = tf.squeeze(F)
F_squeezed.shape

TensorShape([50])

### **One hot Encoding**

representing categorical variables as numbers

In [ ]:
some_list = [0,1,2,3] # could be red, blue, green, yello
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list,depth=5) # can see what depth is

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list,depth=4,on_value='hey',off_value='hi')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'hey', b'hi', b'hi', b'hi'],
       [b'hi', b'hey', b'hi', b'hi'],
       [b'hi', b'hi', b'hey', b'hi'],
       [b'hi', b'hi', b'hi', b'hey']], dtype=object)>

In [ ]:
print('hello world')

hello world


### **Squaring, log, root**

In [ ]:
G = tf.range(0,10)
G

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(G,dtype=tf.float32)) # since int32 not allowed, look up other functions as well

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.       , 1.       , 1.4142135, 1.7320508, 2.       , 2.236068 ,
       2.4494898, 2.6457512, 2.828427 , 3.       ], dtype=float32)>

### **GPU/ TPU access**

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
# as we can see, there is no GPU
tf.config.list_physical_devices('GPU')

[]

In [ ]:
# edit --> notebook settings --> GPU (you can also get a TPU but that needs more setup)
import tensorflow as tf
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Fri Sep 29 10:39:55 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P8    10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# GPU is CUDA - enabled, thus tf used it automatically whenever possible